#!/bin/bash
#
# OPEW uninstaller
# @description This utility script 
# @license GNU GPL 3.0
# @version Beta - 04/02/2012
#

# check if run as root
if [ "`id -u`" -ne 0 ]; then
       echo "ERROR: "
       echo "You must run this script like a root user. You can't continue..."
       exit 1
fi

# check PATH environment variable
if [ -z $PATH ]; then
	echo "The PATH environment variable is empty. Cannot continue with the installation process..."
	echo "Must be defined in order to run the installer properly. "
	echo "Please, copy and ejecute this (or your customized PATH environment): " 
	echo 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
	exit 1
fi

echo "##################################"
echo "        OPEW uninstaller "
echo "##################################"
echo " "
read -p "Do you want to uninstall OPEW from this system? (y|N): " response
case $response in
	y|Y|yes|Yes|YES)
		echo " "
		echo "Stating unintall process..."
	;;
 	*)
	echo "You select NO. Exiting."
	exit 0
	;;
esac
sleep 1
echo " "

echo "Stoping services... "
/opt/opew/scripts/opew stop 
echo " "

echo -n "Removing users... "
userdel opew
userdel opew-httpd
userdel opew-mysql
userdel opew-postgres
sleep 1
echo "done!"

echo -n "Removing files... "
rm -rf /opt/opew
sleep 1
echo "done!"

sleep 1
echo " "
echo "OPEW was uninstalled from this system."
exit 0
