#!/bin/bash
# 
# This code is a part of OPEW project <http://opew.sf.net>
# @description 	Bash utility to make OPEW portable
# @author	Tomas Aparicio <tomas@rijndael-project.com>
# @license	GNU GPL 3.0
# @version	Beta - 13/05/2012
# 

_VERSION=1.0.1
_OUTPUT="opew-portable-$_VERSION-$(hostname)-$(date +%Y%m%d)"

#
# Gets the installer bash code
# 
function installer
{
	# count the files
	local nlines=`wc -l opew-files.log | awk '{ print $1; }'`
	cat /opt/opew/stack/scripts/installer.bash | sed -e "s/{LINES}/$nlines/g"
}

# check PATH environment variable
if [ -z $PATH ]; then
	echo "The PATH environment variable is empty. Cannot continue."
	echo "Please, copy and ejecute this (or your customized PATH environment): " 
	echo 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
	exit 1
fi

# check if run as root
if [ "`id -u`" -ne 0 ];	then
       	echo "ERROR: "
	echo "You must run the installer like a root user. You can't continue..."
       	exit 1
fi

cat <<- _EOF_
With this utility you can move the current OPEW stack
complety to another computer including your projects.

Note: the services will be stopped.
_EOF_

read -p "Do you want to make OPEW portable? (y/n): " res
case $res in
y|Y|yes|YES|Yes) 
	echo " "
;;
*)
	echo "Exiting."
	exit 0
;;
esac

echo "Stopping services... "
/opt/opew/scripts/opew stop
echo " "

while : ; do
    read -p "Output directory [$PWD]: " res
    echo " "
    if [ "$res" == "/opt/opew" ] || [ "$res" = "/opt/opew/" ]; then
		echo "/opt/opew is not a valid path. Enter another."
	elif [ -z $res ]; then
		DIR="$PWD"
		echo "Using the default output folder: $PWD"
		break
	elif [ -d $res ]; then
		DIR="$res"
		echo "Output folder will be: $DIR"
		break
	elif [ $res == 'x']; then
		echo "Exiting."
		exit 0
	else
		echo "The path entered is not a directory or invalid"
	fi
done

echo " "
read -p "Press enter to continue..." 

sleep 1
echo "Starting packaging. This may take some minutes..."
echo " "

cd /opt/
tar czvf "$DIR/$_OUTPUT.tar.gz" opew/ > opew-files.log

echo " "
echo "Building the portable installer... "
sleep 1

installer > installer.bash
cat installer.bash "$DIR/$_OUTPUT.tar.gz" > "$DIR/$_OUTPUT.bin"

echo "Done! Now cleaning... "
sleep 1

rm -f installer.bash
rm -f opew-files.log
rm -f "$DIR/$_OUTPUT.tar.gz"

sleep 1

cat <<- _EOF_
Your OPEW portable version is located on: 
$DIR/$_OUTPUT.bin

You can reinstall OPEW in another computer simply doing: 
# chmod +x $_OUTPUT.bin"
# ./$_OUTPUT.bin"

Remember you must start manually the services you need via:
/opt/opew/scripts/opew start <service>
_EOF_

exit 0
